version: '2'
services:
  tcc-postgresql:
    extends:
      file: postgresql.yml
      service: tcc-postgresql
    container_name: tcc-postgres

  tcc-document-minio:
    extends:
      file: minio.yml
      service: tcc-document-minio
    container_name: tcc-document-minio