version: '2'
services:
  tcc-postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=tcc
      - POSTGRES_PASSWORD=tcc
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432