server:
  port: 8081

cloud:
  aws:
    s3:
      bucket-name: document
      path-style-enabled: true
      url: http://localhost:9000
    credential:
      access-key: tcc
      secret-key: tccsecretkey

#only for dev purposes
logging:
  level:
    io:
      tcc: DEBUG