spring:
  jpa:
    show-sql: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified}
    username: ${DATABASE_USERNAME:tcc}
    password: ${DATABASE_PASSWORD:tcc}
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
#    drop-first: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER_EMAIL}
    password: ${MAIL_SENDER_PASSWORD}
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

#only for dev purposes
logging:
  level:
    io:
      tcc: DEBUG
    org:
      springframework:
        mail: OFF
