spring:
  jpa:
    show-sql: true
  datasource:
    username: postgres
    password: tcc
    url: jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: tccportalmaker@gmail.com
    password: sgixornounszexke
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
#    drop-first: true

#only for dev purposes
logging:
  level:
    io:
      tcc: DEBUG

