spring:
  datasource:
    username: tcc
    password: tcc
    url: jdbc:postgresql://localhost:5432/postgres
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
server:
  port: 10000
#    drop-first: true