spring:
  datasource:
    username: tcc
    password: tcc
    url: jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
server:
  port: 8080
#    drop-first: true

#only for dev purposes
logging:
  level:
    io:
      tcc: DEBUG